{{- if .Values.eso.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cnpgdb.fullname" . }}-db-backup-aws-creds
spec:
  refreshInterval: {{ .Values.eso.databaseBackup.refreshInterval }}
  target:
    name: {{ include "cnpgdb.fullname" . }}-db-backup-aws-creds
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: {{ include "cnpgdb.fullname" . }}-db-backup-aws-creds
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: {{ include "cnpgdb.fullname" . }}-db-backup-aws-creds
spec:
  path: {{ .Values.eso.databaseBackup.credsPath }}
  method: "GET"
  parameters:
    ttl: {{ .Values.eso.databaseBackup.ttl }}
  provider:
    server: {{ .Values.eso.databaseBackup.vaultUrl}}
    auth:
      kubernetes:
        mountPath: {{ .Values.eso.databaseBackup.auth.mountPath }}
        role: {{ .Values.eso.databaseBackup.auth.role }}
        serviceAccountRef:
          name: {{ include "cnpgdb.fullname" . }}-db-backup-aws-creds
{{- end }}
