apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "incron-backuper.fullname" . }}
  labels:
    {{- include "incron-backuper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "incron-backuper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "incron-backuper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts: 
          - name: incrontab
            path: /var/spool/incron
          - name: target-vol
            path: /target
          - name: src-vol
            path: /src  
            readOnly: true          
          env:
          - name: TGT_DIR
            value: /target
          - name: KEYSERVER
            value: {{ .Values.backuper.keyserver }}
          - name: KEY_ID
            value: {{ .Values.backuper.keyId }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:  
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: incrontab
        configMap: 
          name: {{ include "incron-backuper.fullname" . }}
      - name: target-vol
        persistentVolumeClaim:
          claimName: {{ include "incron-backuper.fullname" . }}-tgt-pvc
      - name: src-vol
        hostPath: {{ .Values.backuper.srcVolume.hostPath }}
        type: Directory
